### ISSUE TITLE
ToDo: Provision a backend and configure updates to sync

### ISSUE THREAD

**Issue by THOM-AwS** [THOM-AwS/project-phoenix#4]
- [ ] choose a backend service (S3, Dynamo, RDS)
- [ ] deploy infra required to interface with AWS IOT
- [ ] Connect up rules to feed that data into a table
