### ISSUE TITLE
ToDo: Create front end application

### ISSUE THREAD

**Issue by THOM-AwS** [THOM-AwS/project-phoenix#5]
- [ ] Choose front end to use (Amplify, S3 and lambda)
- [ ] Design UI
- [ ] Create functional prototype
- [ ] collect data from DB Table and present
